apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: synergychat-api
  ports:
    - protocol: TCP # TCP will allow us to use HTTP
      port: 80
      targetPort: 8080
